# Generated by Django 3.1.7 on 2021-03-29 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_dish'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_group', models.CharField(choices=[('Y', 'Ясли'), ('S', 'Старшая группа')], max_length=300)),
            ],
            options={
                'verbose_name': 'День приема пищи',
                'verbose_name_plural': 'Дни приема пищи',
            },
        ),
        migrations.CreateModel(
            name='Eating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_eating', models.CharField(choices=[('Z', 'Завтрак'), ('SZ', 'Второй завтрак'), ('O', 'Обед'), ('P', 'Полдник')], max_length=300)),
                ('dish', models.ManyToManyField(to='menu.Dish')),
                ('eating', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='result', to='menu.day', verbose_name='Прием пищи')),
            ],
            options={
                'verbose_name': 'Результат к предмету',
                'verbose_name_plural': 'Результаты к предметам',
            },
        ),
    ]
