# Generated by Django 3.1.7 on 2021-03-29 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_day_eating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eating',
            options={'verbose_name': 'Прием пищи', 'verbose_name_plural': 'Приемы пищи'},
        ),
        migrations.AddField(
            model_name='day',
            name='day_week',
            field=models.CharField(choices=[('MON', 'Понедельник'), ('TUE', 'Вторник'), ('SAT', 'Среда'), ('THU', 'Четверг'), ('FRI', 'Пятница')], default=1, max_length=300, verbose_name='День недели'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='day',
            name='parity_of_the_week',
            field=models.CharField(choices=[('EVEN', 'Четная неделя'), ('ODD', 'Нечетная неделя')], default=1, max_length=300, verbose_name='Четность недели'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='day',
            name='type_group',
            field=models.CharField(choices=[('Y', 'Ясли'), ('S', 'Старшая группа')], max_length=300, verbose_name='Тип группы'),
        ),
        migrations.AlterField(
            model_name='eating',
            name='dish',
            field=models.ManyToManyField(to='menu.Dish', verbose_name='Блюда'),
        ),
        migrations.AlterField(
            model_name='eating',
            name='type_eating',
            field=models.CharField(choices=[('Z', 'Завтрак'), ('SZ', 'Второй завтрак'), ('O', 'Обед'), ('P', 'Полдник')], max_length=300, verbose_name='Какой приём пищи?'),
        ),
    ]
