# Generated by Django 3.1.7 on 2021-04-04 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_auto_20210329_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='count',
        ),
        migrations.RemoveField(
            model_name='product',
            name='unit',
        ),
        migrations.AlterField(
            model_name='eating',
            name='eating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eating', to='menu.day', verbose_name='Прием пищи'),
        ),
        migrations.CreateModel(
            name='ProductInDish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='Норма на чел.')),
                ('unit', models.CharField(max_length=255, verbose_name='Единица измерения')),
                ('product', models.ManyToManyField(to='menu.Product', verbose_name='Продукт')),
            ],
        ),
    ]
