# Generated by Django 3.1.7 on 2021-04-04 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_auto_20210404_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='productindish',
            name='dish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dish', to='menu.dish', verbose_name='Блюдо'),
        ),
        migrations.RemoveField(
            model_name='productindish',
            name='product',
        ),
        migrations.AddField(
            model_name='productindish',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='menu.product', verbose_name='Продукт'),
        ),
    ]
