# Generated by Django 3.1.7 on 2021-04-04 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_auto_20210404_2155'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productindish',
            options={'verbose_name': 'Продукт в блюде', 'verbose_name_plural': 'Продукты в блюде'},
        ),
    ]
