# Generated by Django 3.1.7 on 2021-04-05 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_auto_20210404_2202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productindish',
            old_name='dish',
            new_name='dish_and_product',
        ),
    ]
