# Generated by Django 3.1.7 on 2021-04-05 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_auto_20210405_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productindish',
            name='count',
            field=models.FloatField(verbose_name='Норма на чел.'),
        ),
    ]
