# Generated by Django 3.1.7 on 2021-04-05 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0011_children'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Children',
        ),
    ]
