# Generated by Django 3.1.7 on 2021-04-06 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0012_delete_children'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='Количество детей')),
            ],
            options={
                'verbose_name': 'Учет детей',
                'verbose_name_plural': 'Учет детей',
            },
        ),
    ]
