# Generated by Django 3.1.7 on 2021-04-06 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0013_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='type_group',
            field=models.CharField(choices=[('Y', 'Ясли'), ('S', 'Старшая группа')], default=1, max_length=300, verbose_name='Тип группы'),
            preserve_default=False,
        ),
    ]
