# Generated by Django 3.1.7 on 2021-04-18 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0014_person_type_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='productindish',
            name='unit_after',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Единица измерения после перевода'),
        ),
    ]
