# Generated by Django 3.1.7 on 2021-04-18 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0015_productindish_unit_after'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(blank=True, null=True, verbose_name='Дата')),
                ('junior_group', models.IntegerField(blank=True, null=True, verbose_name='Младшая группа')),
                ('older_group', models.IntegerField(blank=True, null=True, verbose_name='Старшая группа')),
            ],
            options={
                'verbose_name': 'Учет посещаемости',
                'verbose_name_plural': 'Учет посещаемости',
            },
        ),
    ]
