# Generated by Django 3.1.7 on 2021-04-18 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0016_attendance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Учет детей для расчета на 10 дней', 'verbose_name_plural': 'Учет детей для расчета на 10 дней'},
        ),
    ]
