# Generated by Django 3.1.7 on 2021-04-18 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0018_day_day'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.AddField(
            model_name='day',
            name='junior_group',
            field=models.IntegerField(blank=True, null=True, verbose_name='Младшая группа'),
        ),
        migrations.AddField(
            model_name='day',
            name='older_group',
            field=models.IntegerField(blank=True, null=True, verbose_name='Старшая группа'),
        ),
    ]
