# Generated by Django 3.1.7 on 2021-04-18 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0019_auto_20210418_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='junior_group',
        ),
        migrations.RemoveField(
            model_name='day',
            name='older_group',
        ),
        migrations.AddField(
            model_name='day',
            name='count_person',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество детей'),
        ),
    ]
