# Generated by Django 3.1.7 on 2021-04-18 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0021_auto_20210418_1726'),
    ]

    operations = [
        migrations.RenameField(
            model_name='day',
            old_name='day',
            new_name='date',
        ),
    ]
