# Generated by Django 3.1.7 on 2021-05-04 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0022_auto_20210418_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eating',
            name='dish',
            field=models.ManyToManyField(related_name='dish_dish', to='menu.Dish', verbose_name='Блюда'),
        ),
    ]
