# Generated by Django 3.1.7 on 2021-05-04 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0023_auto_20210504_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eating',
            name='dish',
            field=models.ManyToManyField(to='menu.Dish', verbose_name='Блюда'),
        ),
    ]
