# Generated by Django 3.1.7 on 2022-01-25 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0024_auto_20210504_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='carbohydrates',
            field=models.FloatField(blank=True, null=True, verbose_name='Углеводы'),
        ),
        migrations.AddField(
            model_name='product',
            name='fats',
            field=models.FloatField(blank=True, null=True, verbose_name='Жиры'),
        ),
        migrations.AddField(
            model_name='product',
            name='protein',
            field=models.FloatField(blank=True, null=True, verbose_name='Белки'),
        ),
    ]
