# Generated by Django 3.1.7 on 2022-01-25 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0025_auto_20220125_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='caloric',
            field=models.FloatField(blank=True, null=True, verbose_name='Калорийность'),
        ),
        migrations.AddField(
            model_name='productindish',
            name='carbohydrates',
            field=models.FloatField(blank=True, null=True, verbose_name='Углеводы'),
        ),
        migrations.AddField(
            model_name='productindish',
            name='fats',
            field=models.FloatField(blank=True, null=True, verbose_name='Жиры'),
        ),
        migrations.AddField(
            model_name='productindish',
            name='protein',
            field=models.FloatField(blank=True, null=True, verbose_name='Белки'),
        ),
    ]
