# Generated by Django 3.1.7 on 2022-01-25 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0026_auto_20220125_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='productindish',
            name='caloric',
            field=models.FloatField(blank=True, null=True, verbose_name='Калорийность'),
        ),
    ]
